### ISSUE TITLE
Drag&Drop doesn't work when uploading an .exe

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Files#2]
Not sure if this error occurs because of the extension of the file. The name is "fg752p.exe" so it doesn't contain weird characters. The error that console shows is:

```
TypeError: e.originalEvent.dataTransfer.items is undefined
desktop.js (line 272, col 28)
The connection to wss://socket.inevio.com/ was interrupted while the page was loading.
core.js (line 2305)
```

And then a banner with "The connection with the server was lost" appears.

**Comment by Robby2023** [comment]
By the way, there is no problem uploading the file if you use the button of upload instead of drag&drop.

**Comment by javiergarmon** [comment]
Working on it. Thank you :smile:

**Comment by javiergarmon** [comment]
Fixed and closed!
